/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacao;
import dados.Connections;
import dados.DvdDAO;
import entidades.Dvd;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_NO_CANCEL_OPTION;

/**
 *
 * @author lucas
 */
public class ProgramaProducao extends javax.swing.JFrame {

    /**
     * Creates new form ProgramaProducao
     */
    public ProgramaProducao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIncluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        txtCodigo = new javax.swing.JTextField();
        txtBanda = new javax.swing.JTextField();
        txtAlbum = new javax.swing.JTextField();
        txtAno = new javax.swing.JTextField();
        txtEstoque = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        lblBanda = new javax.swing.JLabel();
        lblAlbum = new javax.swing.JLabel();
        lblAno = new javax.swing.JLabel();
        lblEstoque = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JButton();
        btnApagar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIncluir.setForeground(new java.awt.Color(255, 0, 0));
        btnIncluir.setText("Inlcuir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnPesquisar.setForeground(new java.awt.Color(255, 0, 0));
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        lblCodigo.setForeground(new java.awt.Color(0, 0, 255));
        lblCodigo.setText("Código");

        lblBanda.setForeground(new java.awt.Color(0, 0, 255));
        lblBanda.setText("Banda");

        lblAlbum.setForeground(new java.awt.Color(0, 0, 255));
        lblAlbum.setText("Álbum");

        lblAno.setForeground(new java.awt.Color(0, 0, 255));
        lblAno.setText("Ano");

        lblEstoque.setForeground(new java.awt.Color(0, 0, 255));
        lblEstoque.setText("Estoque");

        btnAtualizar.setForeground(new java.awt.Color(255, 0, 0));
        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnApagar.setForeground(new java.awt.Color(255, 0, 0));
        btnApagar.setText("Apagar");
        btnApagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarActionPerformed(evt);
            }
        });

        btnLimpar.setForeground(new java.awt.Color(255, 0, 0));
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBanda)
                            .addComponent(lblAlbum)
                            .addComponent(lblCodigo)
                            .addComponent(lblAno)
                            .addComponent(lblEstoque))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBanda, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIncluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAtualizar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(btnApagar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimpar)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBanda))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAlbum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlbum))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAno))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstoque))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnPesquisar)
                    .addComponent(btnAtualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApagar)
                    .addComponent(btnLimpar))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
      Dvd d = new Dvd (
              Integer.parseInt(txtCodigo.getText()),
              txtBanda.getText(),
              txtAlbum.getText(),
              Integer.parseInt(txtAno.getText()),
              Integer.parseInt(txtEstoque.getText())
              );
       
      DvdDAO dao = new DvdDAO();
        try{
            
            //Insere os dados no banco de dados
            dao.CadastraDvd(d);
            
            //Limpar o campo de texto
            txtCodigo.setText("");
            txtBanda.setText("");
            txtAlbum.setText("");
            txtAno.setText("");
            txtEstoque.setText("");
      
            //Mensagem de confirmação
            JOptionPane.showMessageDialog(this, "DVD Cadastrado com sucesso! ");
     
        } catch (Exception ex) {
            Logger.getLogger(ProgramaProducao.class.getCanonicalName()).log(Level.SEVERE, null, ex);
        } 
        
        
      
     
        
        
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
       DvdDAO dao = new DvdDAO();
       try {
           if(dao.PesquisaDvd(Integer.parseInt(txtCodigo.getText())).getAlbum() != "" ){
                //Mensagem de pesquisa de DVD
                JOptionPane.showMessageDialog(this, "DVD encontrado! ");
               
               txtAlbum.setText(dao.PesquisaDvd(Integer.parseInt(txtCodigo.getText())).getAlbum()) ;
               txtBanda.setText("" + dao.PesquisaDvd(Integer.parseInt(txtCodigo.getText())).getBanda()) ;
               txtAno.setText("" + dao.PesquisaDvd(Integer.parseInt(txtCodigo.getText())).getAno()) ;
               txtEstoque.setText("" + dao.PesquisaDvd(Integer.parseInt(txtCodigo.getText())).getEstoque()) ;
               
           } else  {
               //Mensagem de pesquisa não encontrada
               JOptionPane.showMessageDialog(this, "DVD não encontrado! ");
               
               txtCodigo.setText(null);
               txtBanda.setText(null);
               txtAlbum.setText(null);
               txtAno.setText(null);
               txtEstoque.setText(null);
               
           
           }
           
       
       }catch (Exception ex) {
            Logger.getLogger(ProgramaProducao.class.getCanonicalName()).log(Level.SEVERE, null, ex);
        } 
        
        
        
        
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
       DvdDAO dao = new DvdDAO();
       try {
           dao.AtualizarEstoque(Integer.parseInt(txtCodigo.getText()) ,
                                txtBanda.getText(),
                                txtAlbum.getText(),
                                Integer.parseInt(txtAno.getText()),
                                Integer.parseInt(txtEstoque.getText()));
           JOptionPane.showMessageDialog(this, "DVD Atualizado! ");
           
        }catch (Exception ex) {
            Logger.getLogger(ProgramaProducao.class.getCanonicalName()).log(Level.SEVERE, null, ex);
        } 
        
        
        
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarActionPerformed
        DvdDAO dao = new DvdDAO();
        
        int opt = JOptionPane.showConfirmDialog(null, "Deseja realmente  ?", "Selecione a opção...",
        JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
        
        if (opt ==0) {
            try{
            dao.ExcluirDvd(Integer.parseInt(txtCodigo.getText()));
             txtBanda.setText(null);
             txtAlbum.setText(null);
             txtAno.setText(null);
             txtEstoque.setText(null);
            
            } catch  (Exception ex) {
            Logger.getLogger(ProgramaProducao.class.getName()).log(Level.SEVERE, null, ex);
            
            }
        
        
        } else {
        JOptionPane.showMessageDialog(this, "Ação Cancelada"); 
        
        }
        
        
        
        
        
        
    }//GEN-LAST:event_btnApagarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
                txtCodigo.setText(null);
                txtBanda.setText(null);
                txtAlbum.setText(null);
                txtAno.setText(null);
                txtEstoque.setText(null);
        
    }//GEN-LAST:event_btnLimparActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProgramaProducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProgramaProducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProgramaProducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProgramaProducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProgramaProducao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApagar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JLabel lblAlbum;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblBanda;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblEstoque;
    private javax.swing.JTextField txtAlbum;
    private javax.swing.JTextField txtAno;
    private javax.swing.JTextField txtBanda;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtEstoque;
    // End of variables declaration//GEN-END:variables
}
